/*
 * Auto-generated QEMU device: basic_timer
 * Generated by LLHD-to-QEMU converter
 */

#ifndef HW_BASIC_TIMER_H
#define HW_BASIC_TIMER_H

#include "hw/sysbus.h"
#include "qom/object.h"
#include "qemu/timer.h"

#define TYPE_BASIC_TIMER "basic_timer"
OBJECT_DECLARE_SIMPLE_TYPE(basic_timer_state, BASIC_TIMER)

typedef struct basic_timer_state {
    SysBusDevice parent_obj;
    MemoryRegion iomem;

    uint8_t running;
    uint8_t timeout_irq;
    /* icount-based counter */
    uint32_t counter_base;      /* 基准值 */
    int64_t counter_icount_base;  /* 记录时的 icount */
    bool counter_running;
} basic_timer_state;

#endif /* HW_BASIC_TIMER_H */
