/*
 * Auto-generated QEMU device: simple_counter
 * Generated by LLHD-to-QEMU converter
 *
 * Uses ptimer + QEMU_CLOCK_VIRTUAL for counter implementation.
 * Compatible with both icount mode and real-time mode.
 */

#ifndef HW_SIMPLE_COUNTER_H
#define HW_SIMPLE_COUNTER_H

#include "hw/sysbus.h"
#include "hw/ptimer.h"
#include "qom/object.h"
#include "qemu/timer.h"

#define TYPE_SIMPLE_COUNTER "simple_counter"
OBJECT_DECLARE_SIMPLE_TYPE(simple_counter_state, SIMPLE_COUNTER)

typedef struct simple_counter_state {
    SysBusDevice parent_obj;
    MemoryRegion iomem;
    qemu_irq irq;

    /* ptimer-based counter: count */
    ptimer_state *count_ptimer;
    uint8_t count_limit;  /* 计数上限/reload值 */
} simple_counter_state;

#endif /* HW_SIMPLE_COUNTER_H */
