/*
 * Auto-generated QEMU device: watchdog_timer
 * Generated by LLHD-to-QEMU converter
 *
 * Uses ptimer + QEMU_CLOCK_VIRTUAL for counter implementation.
 * Compatible with both icount mode and real-time mode.
 */

#ifndef HW_WATCHDOG_TIMER_H
#define HW_WATCHDOG_TIMER_H

#include "hw/sysbus.h"
#include "hw/ptimer.h"
#include "qom/object.h"
#include "qemu/timer.h"

#define TYPE_WATCHDOG_TIMER "watchdog_timer"
OBJECT_DECLARE_SIMPLE_TYPE(watchdog_timer_state, WATCHDOG_TIMER)

typedef struct watchdog_timer_state {
    SysBusDevice parent_obj;
    MemoryRegion iomem;
    qemu_irq irq;

    uint8_t wdt_reset;
    /* ptimer-based counter: counter */
    ptimer_state *counter_ptimer;
    uint32_t counter_limit;  /* 计数上限/reload值 */
    uint8_t wdt_warning;
    uint32_t enable;  /* input */
    uint32_t feed;  /* input */
    uint32_t timeout_val;  /* input */
} watchdog_timer_state;

#endif /* HW_WATCHDOG_TIMER_H */
