/*
 * Auto-generated QEMU device: gpio_top
 * Generated by LLHD-to-QEMU converter
 *
 * Uses ptimer + QEMU_CLOCK_VIRTUAL for counter implementation.
 * Compatible with both icount mode and real-time mode.
 */

#ifndef HW_GPIO_TOP_H
#define HW_GPIO_TOP_H

#include "hw/sysbus.h"
#include "hw/ptimer.h"
#include "qom/object.h"
#include "qemu/timer.h"

#define TYPE_GPIO_TOP "gpio_top"
OBJECT_DECLARE_SIMPLE_TYPE(gpio_top_state, GPIO_TOP)

typedef struct gpio_top_state {
    SysBusDevice parent_obj;
    MemoryRegion iomem;
    qemu_irq irq;

    uint32_t gpio_debounce;  /* input */
    uint32_t gpio_int_clr;  /* input */
    uint32_t gpio_int_en;  /* input */
    uint32_t gpio_int_level_sync;  /* input */
    uint32_t gpio_int_mask;  /* input */
    uint32_t gpio_int_pol;  /* input */
    uint32_t gpio_int_status;  /* input */
    uint32_t gpio_int_type;  /* input */
    uint32_t gpio_raw_int_status;  /* input */
    uint32_t gpio_rx_data;  /* input */
    uint32_t gpio_sw_data;  /* input */
    uint32_t gpio_sw_dir;  /* input */
    uint32_t presetn;  /* input */
    uint32_t scan_mode;  /* input */
    uint32_t gpio_ext_data;  /* gpio input */
    uint32_t gpio_ext_porta;  /* gpio input */
    uint32_t gpio_in_data;  /* gpio input */
} gpio_top_state;

#endif /* HW_GPIO_TOP_H */
