/*
 * Auto-generated QEMU device: gpio_top
 * Generated by LLHD-to-QEMU converter
 *
 * Uses ptimer + QEMU_CLOCK_VIRTUAL for counter implementation.
 * Compatible with both icount mode and real-time mode.
 */

#ifndef HW_GPIO_TOP_H
#define HW_GPIO_TOP_H

#include "hw/sysbus.h"
#include "hw/ptimer.h"
#include "qom/object.h"
#include "qemu/timer.h"

#define TYPE_GPIO_TOP "gpio_top"
OBJECT_DECLARE_SIMPLE_TYPE(gpio_top_state, GPIO_TOP)

typedef struct gpio_top_state {
    SysBusDevice parent_obj;
    MemoryRegion iomem;
    qemu_irq irq;

    uint32_t ri_gpio_raw_int_status;
    uint32_t gpio_raw_int_status;
    uint8_t gpio_int_level_sync;
    uint32_t ri_gpio_int_type;
    uint8_t gpio_int_en_wen;
    uint32_t ri_gpio_sw_data;
    uint32_t gpio_int_pol;
    uint8_t gpio_int_clk_en;
    uint8_t gpio_debounce_wen;
    uint32_t gpio_ext_data;
    uint8_t gpio_int_level_sync_wen;
    uint32_t gpio_int_type;
    uint32_t gpio_int_clr;
    /* ptimer-based counter: int_k */
    ptimer_state *int_k_ptimer;
    uint32_t int_k_limit;  /* 计数上限/reload值 */
    uint32_t SUPPORT_INT_LEVEL_SYNC_PROC_int_level_sync_in_ff2;
    uint32_t ri_gpio_debounce;
    uint32_t prdata;
    uint32_t ri_gpio_int_level_sync;
    uint8_t gpio_int_clr_wen;
    uint32_t gpio_int_status_edge;
    uint32_t ri_gpio_int_en;
    uint32_t gpio_sw_data;
    uint32_t int_edge_out;
    uint8_t gpio_int_mask_wen;
    uint32_t gpio_sw_dir;
    uint32_t ri_gpio_sw_dir;
    uint8_t gpio_int_pol_wen;
    uint32_t SUPPORT_INT_LEVEL_SYNC_PROC_int_level_sync_in_ff1;
    uint32_t gpio_int_status_level;
    uint32_t ri_gpio_int_mask;
    uint32_t int_level_ff1;
    uint32_t gpio_rx_data_int;
    uint32_t ri_gpio_int_pol;
    uint32_t gpio_int_mask;
    uint32_t gpio_int_en;
    uint8_t unnamed;
    uint32_t debounce_d2;
    uint8_t gpio_sw_data_wen;
    uint32_t ri_gpio_int_status;
    uint8_t gpio_int_type_wen;
    uint32_t int_level_sync_in;
    uint8_t gpio_sw_dir_wen;
    uint32_t gpio_debounce;
    uint32_t ri_gpio_ext_data;
    uint32_t dbclk;  /* input */
    uint32_t dbclk_rstn;  /* input */
    uint32_t gpio_ext_porta;  /* input */
    uint32_t gpio_in_data;  /* input */
    uint32_t gpio_int_status;  /* input */
    uint32_t gpio_rx_data;  /* input */
    uint32_t paddr;  /* input */
    uint32_t pclk;  /* input */
    uint32_t pclk_int;  /* input */
    uint32_t pclk_intr;  /* input */
    uint32_t penable;  /* input */
    uint32_t presetn;  /* input */
    uint32_t psel;  /* input */
    uint32_t pwdata;  /* input */
    uint32_t pwrite;  /* input */
    uint32_t scan_mode;  /* input */
} gpio_top_state;

#endif /* HW_GPIO_TOP_H */
